/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_enerccio_sp_interpret_NativePythonInterpreter */

#ifndef _Included_me_enerccio_sp_interpret_NativePythonInterpreter
#define _Included_me_enerccio_sp_interpret_NativePythonInterpreter
#ifdef __cplusplus
extern "C" {
#endif
#undef me_enerccio_sp_interpret_NativePythonInterpreter_serialVersionUID
#define me_enerccio_sp_interpret_NativePythonInterpreter_serialVersionUID 1i64
#undef me_enerccio_sp_interpret_NativePythonInterpreter_serialVersionUID
#define me_enerccio_sp_interpret_NativePythonInterpreter_serialVersionUID -8039667108607710165i64
/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    load0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_load0
  (JNIEnv *, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    finalize0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_finalize0
  (JNIEnv *, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    doExecuteSingleInstruction
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;Lme/enerccio/sp/compiler/Bytecode;)Lme/enerccio/sp/interpret/ExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_doExecuteSingleInstruction
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    resolveClosure
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_resolveClosure
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    openLocals
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_openLocals
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    pushLocals
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_pushLocals
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    pushEnvironment
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_pushEnvironment
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    call
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_call
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    setupLoop
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_setupLoop
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    acceptIter
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_acceptIter
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    getIter
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)Z
 */
JNIEXPORT jboolean JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_getIter
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    ecall
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_ecall
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    krcall
 * Signature: (Lme/enerccio/sp/compiler/Bytecode;Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_krcall
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    gotoOperation
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_gotoOperation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    jumpIfFalse
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_jumpIfFalse
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    jumpIfTrue
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_jumpIfTrue
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    jumpIfNone
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_jumpIfNone
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    jumpIfNoReturn
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_jumpIfNoReturn
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    makeFuture
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_makeFuture
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    load
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_load
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    loadFuture
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_loadFuture
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    testFuture
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_testFuture
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    loadGlobal
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_loadGlobal
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    pop
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_pop
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    truthValue
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_truthValue
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    push
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_push
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    returnOperation
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_returnOperation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    save
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_save
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    kwarg
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_kwarg
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    saveLocal
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_saveLocal
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    saveGlobal
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_saveGlobal
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    dup
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_dup
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    importOperation
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_importOperation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    swapStack
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_swapStack
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    makeFirst
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_makeFirst
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    unpackSequence
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_unpackSequence
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    unpackKwargs
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_unpackKwargs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    pushLocalContext
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_pushLocalContext
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    resolveArgs
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_resolveArgs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    getAttr
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_getAttr
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    delAttr
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_delAttr
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    setAttr
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_setAttr
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    isinstance
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_isinstance
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    raise
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_raise
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    reraise
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_reraise
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    pushFrame
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_pushFrame
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    pushException
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_pushException
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    yield
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)Lme/enerccio/sp/interpret/ExecutionResult;
 */
JNIEXPORT jobject JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_yield
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    loadDynamic
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_loadDynamic
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    saveDynamic
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_saveDynamic
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    loadBuiltin
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_loadBuiltin
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     me_enerccio_sp_interpret_NativePythonInterpreter
 * Method:    del
 * Signature: (Lme/enerccio/sp/interpret/FrameObject;Ljava/util/Stack;)V
 */
JNIEXPORT void JNICALL Java_me_enerccio_sp_interpret_NativePythonInterpreter_del
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
