package me.enerccio.sp.compiler;

public enum Bytecode {
	NOP, PUSH_ENVIRONMENT, POP_ENVIRONMENT, PUSH_DICT, RETURN,
	POP, PUSH, CALL, GOTO, JUMPIFTRUE, JUMPIFFALSE,
	LOAD, LOADGLOBAL, LOADNONLOCAL, SAVE, SAVEGLOBAL, SAVENONLOCAL
}
